### ISSUE TITLE
ntdll.dll fix

### ISSUE THREAD

**Issue by femdiya** [JuniorDjjr/CrashInfo#2]
Hi @JuniorDjjr.
I found another fix for ntdll.dll:
Problem: The music file (user track radio) cannot be played.
Solution 1: Check the user tracks folder located at : "Documents\GTA San Andreas User Files" and check for corrupted music file or any other file other than *mp3* file format.
Solution 2: Install latest Windows Media Player from Add or remove features or Microsoft's official website.

**Comment by femdiya** [comment]
@JuniorDjjr

**Comment by JuniorDjjr** [comment]
Added

**Comment by femdiya** [comment]
After 2 years lol

**Comment by MinePro120** [comment]
I found another crash where ntdll.dll is mentioned, with CrashInfo having no documented fix (log attached below). I don't think it has anything to do with user tracks though, it seems to happen randomly. 

[gta_sa.exe_2025-08-19_12-32-52.log](https://github.com/user-attachments/files/21852796/gta_sa.exe_2025-08-19_12-32-52.log)
