### ISSUE TITLE
Problem with Proper Fixes (v.1.3) (Game Crashed)

### ISSUE THREAD

**Issue by Jazooxd** [JuniorDjjr/CrashInfo#6]
Hi idk how to contact you so i posted here:

I have problem with your mode "Proper Fixes" (v.1.3)

I found that the following files are causing the error:

Path ---> \Proper Fixes

`gta3.img`

Error:
![Error_gta3 img](https://github.com/user-attachments/assets/400c109b-cfa9-433a-99e3-7e1ef2bed2b1)

`Additional Models`

Error:
![Error](https://github.com/user-attachments/assets/52fa88ec-6085-47de-8674-4f5f13f6d602)

Path ---> Proper Fixes\Map\Maps

`SF, LA, vegas, country`

Error:
![Error](https://github.com/user-attachments/assets/35b7e440-7c99-42ca-868e-47e40b02cee0)

Same Error but different ID (and i have more quantities with this Error)

Path ---> Proper Fixes\Map\Maps

`generic`

Error: - 1.
![Errorss](https://github.com/user-attachments/assets/4dc3eec5-ae44-4359-b83a-1fec249ca2bf)

2.
![sda](https://github.com/user-attachments/assets/436299fc-0297-4a3c-941c-cfcf96835ef2)

anything alse working good only this files make game to crash.... how i can fix this Error?

More information:

Game v. 1.0 US

Screen of my modloader:
![modloader](https://github.com/user-attachments/assets/3399abde-d051-4f8f-8831-e35fba05181c)

I heve this Error in samp (samp v. 0.3.7-R5-1)

**Comment by JuniorDjjr** [comment]
This isn't related to CrashInfo (in fact you are not even using CrashInfo, the first error for example is already documented with solutions on CrashInfo), you just installed Proper Fixes wrongly, looks like because SAMP don't load map and other data files by default (anti-cheat, need to use mods to make it load).
